### ISSUE TITLE
OBC issue(s) when opening on Macbook Pro (Catalina)

### ISSUE THREAD

**Issue by mattpstv** [Deep-Symmetry/open-beat-control#2]
Last login: Wed Jan 22 03:09:38 on console
positive69@PSTVMACBOOK ~ % java -jar /Users/positive69/Downloads/open-beat-control-0.1.0-Preview.jar
2020-Jan-22 21:38:40 INFO [open-beat-control.logs:87] - Open Beat Control version 0.1.0-SNAPSHOT-62-0xdec7 built Mon Jan 20 00:30:32 UTC 2020
2020-Jan-22 21:38:40 INFO [open-beat-control.logs:88] - Java version 13.0.1, Java HotSpot(TM) 64-Bit Server VM, Oracle Corporation
2020-Jan-22 21:38:40 INFO [open-beat-control.logs:89] - Operating system version Mac OS X 10.15.2
2020-Jan-22 21:38:41 INFO [open-beat-control.core:179] - Running OSC server on port 17002
2020-Jan-22 21:38:41 INFO [open-beat-control.core:190] - Waiting for Pro DJ Link devices...
2020-Jan-22 21:38:41 INFO [open-beat-control.core:200] - Pro DJ Link Device Found: DeviceAnnouncement[device:3, name:XDJ-1000MK2, address:192.168.7.197]
2020-Jan-22 21:38:41 INFO [org.deepsymmetry.beatlink.VirtualCdj:588] - Found matching network interface en0 (en0), will use address /192.168.7.254/22 [/192.168.7.255]
2020-Jan-22 21:38:41 INFO [open-beat-control.core:200] - Pro DJ Link Device Found: DeviceAnnouncement[device:4, name:XDJ-1000MK2, address:192.168.7.211]
2020-Jan-22 21:38:45 INFO [open-beat-control.core:121] - Virtual CDJ running as Player 5
2020-Jan-22 21:38:45 INFO [open-beat-control.core:121] - Virtual CDJ running as Player 5
2020-Jan-22 21:38:45 INFO [open-beat-control.core:200] - Pro DJ Link Device Found: DeviceAnnouncement[device:5, name:open-beat-control, address:192.168.7.203]
2020-Jan-22 21:38:45 INFO [org.deepsymmetry.beatlink.dbserver.ConnectionManager:500] - Idle dbserver client closer shutting down.
2020-Jan-22 21:38:45 INFO [org.deepsymmetry.beatlink.data.MetadataFinder:351] - Processing device found, number:5, name:"open-beat-control".
2020-Jan-22 21:38:45 INFO [org.deepsymmetry.beatlink.data.MetadataFinder:351] - Processing device found, number:4, name:"XDJ-1000MK2".
2020-Jan-22 21:38:45 INFO [org.deepsymmetry.beatlink.data.MetadataFinder:351] - Processing device found, number:3, name:"XDJ-1000MK2".
2020-Jan-22 21:38:45 INFO [org.deepsymmetry.beatlink.data.CrateDigger:91] - CrateDigger starting because MetadataFinder[running:true, passive:false, loadedTracks:{}, mountedMediaSlots:[], mountedMediaDetails:[], metadataCacheFiles:{}] has.
2020-Jan-22 21:38:45 INFO [org.deepsymmetry.beatlink.dbserver.ConnectionManager:308] - Player 5 doesn't answer rekordbox port queries, connection refused, not yet ready?
2020-Jan-22 21:38:45 INFO [org.deepsymmetry.beatlink.data.MetadataFinder:884] - Reporting media mounted in SlotReference[player:3, slot:USB_SLOT]
2020-Jan-22 21:38:45 INFO [org.deepsymmetry.beatlink.data.MetadataFinder:884] - Reporting media mounted in SlotReference[player:3, slot:CD_SLOT]
2020-Jan-22 21:38:45 INFO [org.deepsymmetry.beatlink.data.CrateDigger:319] - Fetching rekordbox export.pdb from player 3, slot USB_SLOT
2020-Jan-22 21:38:45 INFO [org.deepsymmetry.beatlink.data.MetadataFinder:884] - Reporting media mounted in SlotReference[player:4, slot:CD_SLOT]
2020-Jan-22 21:38:45 INFO [org.deepsymmetry.beatlink.data.CrateDigger:324] - Finished fetching export.pdb from player 3, slot USB_SLOT; received 270.3 kB in 514ms, 525.9 kB/s.
2020-Jan-22 21:38:45 INFO [org.deepsymmetry.cratedigger.Database:273] - Indexed 75 Tracks.
2020-Jan-22 21:38:45 INFO [org.deepsymmetry.cratedigger.Database:315] - Indexed 19 Artists.
2020-Jan-22 21:38:45 INFO [org.deepsymmetry.cratedigger.Database:357] - Indexed 8 Colors.
2020-Jan-22 21:38:45 INFO [org.deepsymmetry.cratedigger.Database:409] - Indexed 20 Albums.
2020-Jan-22 21:38:45 INFO [org.deepsymmetry.cratedigger.Database:451] - Indexed 13 Labels.
2020-Jan-22 21:38:45 INFO [org.deepsymmetry.cratedigger.Database:493] - Indexed 19 Musical Keys.
2020-Jan-22 21:38:45 INFO [org.deepsymmetry.cratedigger.Database:535] - Indexed 9 Genres.
2020-Jan-22 21:38:45 INFO [org.deepsymmetry.cratedigger.Database:561] - Indexed 63 Artwork Paths.
2020-Jan-22 21:38:45 INFO [org.deepsymmetry.cratedigger.Database:637] - Indexed 1 playlists.
2020-Jan-22 21:38:45 INFO [org.deepsymmetry.cratedigger.Database:668] - Indexed 1 playlist folders.
2020-Jan-22 21:38:45 INFO [org.deepsymmetry.beatlink.data.CrateDigger:331] - Parsing database took 32ms, 2343 tracks/s
2020-Jan-22 21:38:46 INFO [org.deepsymmetry.beatlink.dbserver.ConnectionManager:308] - Player 5 doesn't answer rekordbox port queries, connection refused, not yet ready?
2020-Jan-22 21:38:46 WARN [org.deepsymmetry.beatlink.data.CueList:525] - Was expecting embedded color java.awt.Color[r=0,g=255,b=0] for rekordbox color code 0, but found color java.awt.Color[r=26,g=255,b=0]
2020-Jan-22 21:38:46 WARN [org.deepsymmetry.beatlink.data.CueList:525] - Was expecting embedded color java.awt.Color[r=0,g=255,b=0] for rekordbox color code 0, but found color java.awt.Color[r=26,g=255,b=0]
2020-Jan-22 21:38:46 WARN [org.deepsymmetry.beatlink.data.CueList:525] - Was expecting embedded color java.awt.Color[r=0,g=255,b=0] for rekordbox color code 0, but found color java.awt.Color[r=26,g=255,b=0]
2020-Jan-22 21:38:46 WARN [org.deepsymmetry.beatlink.data.CueList:525] - Was expecting embedded color java.awt.Color[r=0,g=255,b=0] for rekordbox color code 0, but found color java.awt.Color[r=26,g=255,b=0]
2020-Jan-22 21:38:46 WARN [org.deepsymmetry.beatlink.data.CueList:525] - Was expecting embedded color java.awt.Color[r=0,g=255,b=0] for rekordbox color code 0, but found color java.awt.Color[r=26,g=255,b=0]
2020-Jan-22 21:38:46 INFO [org.deepsymmetry.beatlink.data.MetadataFinder:351] - Processing device found, number:1, name:"DJS-1000".
2020-Jan-22 21:38:46 INFO [open-beat-control.core:200] - Pro DJ Link Device Found: DeviceAnnouncement[device:1, name:DJS-1000, address:192.168.7.229]
2020-Jan-22 21:38:46 INFO [org.deepsymmetry.beatlink.dbserver.ConnectionManager:308] - Player 1 doesn't answer rekordbox port queries, connection refused, not yet ready?
2020-Jan-22 21:38:47 INFO [org.deepsymmetry.beatlink.dbserver.ConnectionManager:308] - Player 1 doesn't answer rekordbox port queries, connection refused, not yet ready?
2020-Jan-22 21:38:48 INFO [org.deepsymmetry.beatlink.dbserver.ConnectionManager:308] - Player 5 doesn't answer rekordbox port queries, connection refused, not yet ready?
2020-Jan-22 21:38:49 INFO [org.deepsymmetry.beatlink.dbserver.ConnectionManager:308] - Player 1 doesn't answer rekordbox port queries, connection refused, not yet ready?
2020-Jan-22 21:38:51 INFO [org.deepsymmetry.beatlink.dbserver.ConnectionManager:308] - Player 5 doesn't answer rekordbox port queries, connection refused, not yet ready?
2020-Jan-22 21:38:51 INFO [org.deepsymmetry.beatlink.dbserver.ConnectionManager:323] - Player 5 never responded with a valid rekordbox dbserver port. Won't attempt to request metadata.
2020-Jan-22 21:38:52 INFO [org.deepsymmetry.beatlink.dbserver.ConnectionManager:308] - Player 1 doesn't answer rekordbox port queries, connection refused, not yet ready?
2020-Jan-22 21:38:52 INFO [org.deepsymmetry.beatlink.dbserver.ConnectionManager:323] - Player 1 never responded with a valid rekordbox dbserver port. Won't attempt to request metadata.

**Comment by brunchboy** [comment]
That looks like a normal startup to me, what is the problem you are experiencing? Or what raised concern with you, other than the color stuff that I explained in the other issue?

**Comment by brunchboy** [comment]
Hearing nothing further about this, I am closing it.
