### ISSUE TITLE
It would be nice to be able to set the player number.

### ISSUE THREAD

**Issue by jeffgca** [Deep-Symmetry/open-beat-control#3]
**Is your feature request related to a problem? Please describe.**

Open Beat Control ( OBC ) seems to prefer to grab the next-highest player number on start - it might be useful to specifically set the player number so that it does not clash with other players' settings. 

**Describe the solution you'd like**

jar -java obc.jar --player 3

**Describe alternatives you've considered**

The workaround is to always ensure that the players are online and the Link Session established prior to starting OBC. If OBC is running on a laptop or small device like a raspberry pi, it would be better to be able to "hard-code" which players get which number to prevent clashes and confusion during setup.

**Additional context**

I own 2 XDJs and want to start integrating Ableton Link enabled devices into my DJing - OBC seems to be the best way to do this.

**Comment by brunchboy** [comment]
Hi! Thanks for opening this, it is the first concrete evidence I have that anyone is actually using this tool. 🎉

Beat Link does support assigning a fixed player number to use, so it will be fairly easy to add this feature. I’ll probably have a chance to do it one of the next few evenings, but I would also welcome a pull request if anyone gets to it before me. 😄

**Comment by brunchboy** [comment]
As a side note, I also recently finished reverse-engineering the rest of the startup packets, and expect to be adding a feature to Beat Link that will support the device number being assigned based on the port it is plugged into if you connect it to a DJM-2000 nexus or later, or an XDJ-XZ, which have Ethernet jacks that are tied to specific mixer channels/device numbers. Once that is in place, it will override any self-assigned number or user-configured number, just like it does with hardware players.

**Comment by brunchboy** [comment]
All right, I was able to get to this tonight. I’m pushing changes that will result in a new preview build, and you will be able to use `-d` or `--device-number` to specify what player number you want OBC to use.

**Comment by brunchboy** [comment]
All right, the preview build has updated! Please let me know if this works for you, @therealjeffg

**Comment by jeffgca** [comment]
@brunchboy that's great! I'll try it out once the build updates - it doesn't seem to have yet?

**Comment by jeffgca** [comment]
Forget I said anything - I downloaded the .jar again and tested and indeed the player number gets set correctly and indeed gets into an awkward fight with my player when they are both set to the same number. Amazing!

**Comment by brunchboy** [comment]
That’s right—sorry about the confusion, but with a preview/snapshot build like this there isn’t any obvious sign on GitHub about updating. Once I do an actual formal release, then new changes will go into a new snapshot, until there is another formal release, and so on. Since you’re the first person I know of actually using this, I hadn’t been motivated to do formal releases yet, but once I have some more feedback of things actually working in the field, I’ll be ready to do so.

I’ll see if I can get the latency OSC message working for you as well now.

**Comment by brunchboy** [comment]
Oh, the easiest way to see whether the latest preview/snapshot build has changed since you last downloaded it is to look at the Actions page: https://github.com/Deep-Symmetry/open-beat-control/actions. That shows each time when the action to build the jar has been run.
