### ISSUE TITLE
No Pro DJ Link devices found when running on Windows 10

### ISSUE THREAD

**Issue by alza-bitz** [Deep-Symmetry/open-beat-control#5]
**Describe the bug**
When running on Windows 10, no Pro DJ Link devices are found.

**To reproduce**
1. Connect Pro DJ Link devices to the PC via ethernet (in this case 2 x CDJ-2000NXS2, 1x DJM-900NXS2)
2. Run the app `java -jar .\open-beat-control-0.1.1.jar`
3. The app doesn't find any devices
```
PS D:\Downloads> java -jar .\open-beat-control-0.1.1.jar
2021-Jan-31 20:43:15 INFO [open-beat-control.logs:86] - Open Beat Control version 0.1.1 built Mon Dec 28 23:45:36 UTC 2020
2021-Jan-31 20:43:15 INFO [open-beat-control.logs:87] - Java version 11.0.10, OpenJDK 64-Bit Server VM, AdoptOpenJDK
2021-Jan-31 20:43:15 INFO [open-beat-control.logs:88] - Operating system version Windows 10 10.0
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by clojure.lang.InjectedInvoker/0x0000000800231840 (file:/D:/Downloads/open-beat-control-0.1.1.jar) to method sun.nio.ch.DatagramSocketAdaptor.bind(java.net.SocketAddress)
WARNING: Please consider reporting this to the maintainers of clojure.lang.InjectedInvoker/0x0000000800231840
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2021-Jan-31 20:43:15 INFO [open-beat-control.core:193] - Running OSC server on port 17002
2021-Jan-31 20:43:15 INFO [open-beat-control.core:206] - Waiting for Pro DJ Link devices...
```
**Expected behaviour**
The app finds the connected devices.

**Desktop (please complete the following information):**
 - OS: Windows 10 2004 19041.746, x64
 - Java Version
 ```
PS D:\Downloads> java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
```
 - Project Version 0.1.1

**Additional context**
- Pro DJ Link is working fine when I use Rekordbox, it is able to find all the connected devices.
  - Note: I'm not running Rekordbox at the same time as Open Beat Control though.
- I tried Carabiner as well for comparison, but that also doesn't find any connected devices:
```
PS D:\Downloads\Carabiner_Win_x64> .\Carabiner.exe
Starting Carabiner 1.1.5 on port tcp://127.0.0.1:17000
Link bpm: 120 Peers: 0 Connections: 0
```

**Comment by brunchboy** [comment]
You likely have a firewall issue or some other port conflict, that almost inevitably is what these issues turn out to be. It sounds like you might have already reviewed the troubleshooting section in the Beat Link Trigger user guide, but if you haven’t, please do. And if that doesn’t solve your issue, please join the Beat Link Trigger gitter chat channel, and ask for help there. Kevinnns is very good at helping people sort out Windows network issues.

**Comment by brunchboy** [comment]
Also, Carabiner doesn’t talk to DJ link devices, I am not sure what you were trying to do with it, or how you tried to use it?

**Comment by brunchboy** [comment]
In any case, this kind of help is best pursued on the Gitter channel.

**Comment by brunchboy** [comment]
Here’s a link to the gitter channel in case I am mis-remembering that I put it in the Open Beat Control documentation. (Sorry, I am really buried in some deep work in Beat Link that is going to give us access to a lot more features in the near future, so I am probably being more terse and disjointed than usual in responding here, which is why the channel is better for help requests, there are more people with more expertise who can help there.) https://gitter.im/brunchboy/beat-link-trigger

**Comment by alza-bitz** [comment]
Hi @brunchboy you were correct, it was a network/firewall issue on my side, I've fixed that now and it's working fine 🙂

**Comment by brunchboy** [comment]
Thanks so much for confirming that, @alzadude and I wish you a fun and successful project!
